server:
  port: 8080
  servlet:
    context-path: /r

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/service"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "50g5FQRcibzntcI41QcBhxNjKS0jTTtA9BNPQmJgSnjA4ZJCd3Iq2lu2v8MjvQ0I"